version: "3.2"
services:
  api:
    image: flask_api
    build:
      context: ./api
    command: "gunicorn --workers=8 --bind 0.0.0.0:5000 views:app"
    ports:
      - "80:5000"
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - redis
      - model

  redis:
    image: redis:5.0.6

  model:
    image: ml_service
    build:
      context: ./model
    command: "python3 /src/ml_service.py"
    depends_on:
      - redis
