version: "3.2"
services:
  api:
    image: ml_api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "80:80"
    tty: true
    networks:
      - app-tier

  model:
    image: model
    build:
      context: ./
      dockerfile: ./model/Dockerfile
    tty: true
    networks:
      - app-tier

  # redis:
  #   image: redis:5.0.6
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - app-tier

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - app-tier
  

networks:
  app-tier:
    driver: bridge